### ISSUE TITLE
How to fix cors issue

### ISSUE THREAD

**Issue by zakrian07** [fdciabdul/Google-Drive-Player#6]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://google-drive-player-backed.fdciabdul.repl.co/?url=1ZoeKC_7Sbh6UJn9cyq1CnyHt6Tgv06YW. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
coming here
https://google-drive-player.netlify.app/

**Comment by fdciabdul** [comment]
there's no cors issue in the backend , the repl url is expired 

i'm changing to new url, you can check it on here https://gdrive.demo.imtaqin.id/

updated in frontend too https://google-drive-player.netlify.app/

**Comment by zakrian07** [comment]
[image: image.png]

**Comment by zakrian07** [comment]
$ yarn start
yarn run v1.22.19
$ node main.js
Server listening on port 8080
/home/singhera/projects/Google-Drive-Player-Backed/Google-Drive-Player-Backed/node_modules/gdurl/src/gDrive.js:97
    throw new Error("Error while fetching the media link. " + error.message);
          ^

Error: Error while fetching the media link. cheerio is not defined
    at googleDrive.getMediaLink (/home/singhera/projects/Google-Drive-Player-Backed/Google-Drive-Player-Backed/node_modules/gdurl/src/gDrive.js:97:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/singhera/projects/Google-Drive-Player-Backed/Google-Drive-Player-Backed/main.js:140:18

Node.js v18.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. my local showing this when i run backend
